config/routes.rb
Rails.application.routes.draw do

	root 'application#index'

	resources :groups do
		get "members"      => "groups#index_members"
		get "news"         => "groups#index_news"
		get "groups"       => "groups#index_groups"
		get "groups/new"   => "groups#local_new_group"
		get "projects"     => "groups#index_projects"
		get "projects/new" => "groups#local_new_project"
	end

	resources :articles
	resources :projects
	resources :units
	resources :users do
		get "friends"      => "users#index_friends"
		get "news"         => "users#index_news"
		get "groups"       => "users#index_groups"
		get "projects"     => "users#index_projects"
	end

	resources :places
	resources :people

	get "edges/addfriend" => "edges#user_add_friend"
	get "edges/delfriend" => "edges#user_del_friend"

	get "edges/follow"   => "edges#user_follow_node"
	get "edges/enter"    => "edges#user_enter_group"
	get "edges/visits"   => "edges#user_visits"
	get "edges/lives"    => "edges#user_lives"
	post "edges/update"   => "edges#update"

	get  "/login" => "sessions#new"
	post "/login" => "sessions#create"


	get "/home"               => "home#show"
	get "/home/:edge"         => "home#show"

	get "/home/contacts"      => "people#index"
	get "/home/contacts/new"  => "people#new"


	#get "/home/:p"  => "home#index"




	get "/node/:id"           => "public#show"
	#get "/node/:id/:edge" => "public#show_edge"

  # Example of regular route:
  #   get 'products/:id' => 'catalog#view'

  # Example of named route that can be invoked with purchase_url(id: product.id)
  #   get 'products/:id/purchase' => 'catalog#purchase', as: :purchase

  # Example resource route (maps HTTP verbs to controller actions automatically):
  #   resources :products

  # Example resource route with options:
  #   resources :products do
  #     member do
  #       get 'short'
  #       post 'toggle'
  #     end
  #
  #     collection do
  #       get 'sold'
  #     end
  #   end

  # Example resource route with sub-resources:
  #   resources :products do
  #     resources :comments, :sales
  #     resource :seller
  #   end

  # Example resource route with more complex sub-resources:
  #   resources :products do
  #     resources :comments
  #     resources :sales do
  #       get 'recent', on: :collection
  #     end
  #   end

  # Example resource route with concerns:
  #   concern :toggleable do
  #     post 'toggle'
  #   end
  #   resources :posts, concerns: :toggleable
  #   resources :photos, concerns: :toggleable

  # Example resource route within a namespace:
  #   namespace :admin do
  #     # Directs /admin/products/* to Admin::ProductsController
  #     # (app/controllers/admin/products_controller.rb)
  #     resources :products
  #   end
end

app/models/group.rb
class Group < Unit
	attr_accessor :email, :phone, :facebook, :is_public
	attr_accessor :_local_id

	has_many "super",     edge:"has_sons",     type: "out"
	has_many "groups",    edge:"has_sons",     type: "in"
	has_many "projects",  edge:"has_projects", type: "out"
	has_many "members",   edge:"has_members",  type: "out"
	has_many "followers", edge:"follows",      type: "in"

	has_many "articles",  edge:"has_articles", type: "out"

	def create(author)
		self.save
		self.members.put author
		if _local_id.present?
			self.super.put(_local_id)
		end
	end


	def thumbnail
		if File.exists?("public/imagens/#{@id}.jpg")
			return "/imagens/#{@id}.jpg"
		else
			return "/defaults/group.png"
		end
	end
end

app/controllers/groups_controller.rb
class GroupsController < ApptNodeController
	def index
		@groups = Group.all
		nodepkg_render("groups/index",@groups)
	end

  # GET /units/1
  # GET /units/1.json
	#def show
		#node_render("show",@group)
		#render "show",locals:{node:@group, main: "", user: current_user}
	#end

	def index_news
		@super  = Group.find(params[:group_id])
		@articles = @super.articles.all
		node_render("show", @super, "articles/index", @articles)
	end

	def index_groups
		@super  = Group.find(params[:group_id])
		@groups = @super.groups.all
		node_render("show", @super, "groups/index", @groups)
	end


	def local_new_group
		#@group = Group.find(params[:group_id])
		@node  = Group.new
		@node._local_id = params[:group_id]
		render "new"
	end

	def index_members
		@super  = Group.find(params[:group_id])
		@members = @super.members.all
		node_render("show", @super, "users/index", @members)
	end


	def index_projects
		@super  = Group.find(params[:group_id])
		@projects = @super.projects.all
		node_render("show", @super, "projects/index", @projects)
	end

	def local_new_project
		#@group = Group.find(params[:group_id])
		@node  = Project.new
		@node._local_id = params[:group_id]
		render("projects/new")
	end

protected
	def node_create(args={})
		return Group.new(args)
	end

	def node_params
		params.require(:group).permit(:code, :name, :_local_id)
	end

end

app/views/groups/_form.html.erb
<%= form_for(@node) do |f| %>
	<% if @node.errors.any? %><div id="error_explanation">
		<h2><%= pluralize(@node.errors.count, "error") %> prohibited this user from being saved:</h2>
		<ul><% @node.errors.full_messages.each do |message| %>
			<li><%= message %></li>
		<% end %></ul>
	</div><% end %>

	<div class="field">
		<%= f.label :code %><br>
		<%= f.text_field :code, class: "form-control" %>
	</div>
	<div class="field">
		<%= f.label :name %><br>
		<%= f.text_field :name, class: "form-control" %>
	</div>
	<div class="field">
		<%= f.label :email %><br>
		<%= f.text_field :email, class: "form-control" %>
	</div>
	<div class="field">
		<%= f.label :phone %><br>
		<%= f.text_field :phone, class: "form-control" %>
	</div>


	<div class="field">
		<%= f.label :scope %><br>
		<%= f.text_field :_local_id, class: "form-control"%>
	</div>

	<div class="actions">
		<%= f.submit class:"btn btn-primary btn-lg btn-block"%>
	</div>
<% end %>

app/views/groups/edit.html.erb
<div class="container">
	<h1 align="center">Editing Group</h1><hr>
	<div class="row"><div class="col-3" align="center">
		<%=image_md(@node)%>
	</div><div class="col-6">
		<%= form_for(@node, as: "node", url: "/edges/update?akk=thumbnail", method:"post") do |f| %>
			<%= f.hidden_field :id %>
			<%= f.label :file %>
			<%= f.file_field :bitstream %>
			<%= f.submit "Upload novo Thumbnail", class: "btn btn-primary" %>
		<% end %>
	</div></div><hr>
	<%= render 'form' %>
</div>

app/views/groups/index.html.erb
<p id="notice"><%= notice %></p>

<%=title "Grupos",count: nodepkg.count, add: "opa"%>
<div class="row"><% nodepkg.each do |group| %>
	<div class="col-4"><%=card(group)%></div>
<%end%></div>



<%= link_to 'New Group', new_group_path %>

app/views/groups/new.html.erb
<div class="container">
	<h1 align="center">Novo Grupo</h1>
	<%= render 'form' %>
</div>

app/views/groups/show.html.erb
<%meta title: "Neex - #{node.name}"%>
<%metamagic image_src: "#{request.host}#{node.thumbnail}"%>
<%metamagic name: node.name %>
<%metamagic language: "pt-br" %>


<div class="row"><div class="col-12">

	<div class="row"><div class="col-12">
		<div class="jumbotron p-3 p-md-5 text-white" style="background-image: url(https://fedoramagazine.org/wp-content/uploads/2016/10/f25-supplemental-wp-chosen-945x400.png); background-size: 100%;">
			<div class="col-md-6 px-0">
				<h1 class="display-4 font-italic"><%=node.name%></h1>
				<p class="lead my-3">descricao</p>
			</div>
		</div>
	</div></div>

</div></div>

<div class="row"><div class="col-3">

	<center><%=image_md(node)%></center><hr>

	<ul class="list-group">
		<li class="list-group-item">
			<a href="<%=node.path%>"><%=fa_icon "home"%> Home</a>
		</li>
		<li class="list-group-item">
			<a href="<%=node.path%>/news"><%=fa_icon "newspaper"%> Noticias</a>
		</li>
		<li class="list-group-item">
			<a href="<%=node.path%>/members"><%=fa_icon "users"%> Membros</a>
		</li>
		<li class="list-group-item">
			<a href="<%=node.path%>/groups">Grupos</a>
		</li>
		<li class="list-group-item">
			<a href="<%=node.path%>/projects"><%=fa_icon "tasks"%> Projetos</a>
		</li>
	</ul><hr>

	<div align="center"><ul class="list-inline">
		<li class="list-inline-item">
			<a href="" target="blank"><h1><%=fa_icon "facebook-square"%></h1></a>
		</li>
		<li class="list-inline-item">
			<a href="" target="blank"><h1><%=fa_icon "twitter-square "%></h1></a>
		</li>
	</ul></div>

	<%if @current_user.present?%>
		<hr><ul class="list-group">
			<li class="list-group-item">
				<%=followed_button(node,@current_user)%>
			</li>
			<li class="list-group-item">
				<%=button_enter(node,@current_user)%>
			</li>
		</ul>
	<%end%>


</div><div class="col-9">
	<p id="notice"><%= notice %></p>

	<%=main%>
</div>