config/routes.rb
Rails.application.routes.draw do

	root 'application#index'

	resources :groups do
		get "members"      => "groups#index_members"
		get "news"         => "groups#index_news"
		get "groups"       => "groups#index_groups"
		get "groups/new"   => "groups#local_new_group"
		get "projects"     => "groups#index_projects"
		get "projects/new" => "groups#local_new_project"
	end

	resources :articles
	resources :projects
	resources :units
	resources :users do
		get "friends"      => "users#index_friends"
		get "news"         => "users#index_news"
		get "groups"       => "users#index_groups"
		get "projects"     => "users#index_projects"
	end

	resources :places
	resources :people

	get "edges/addfriend" => "edges#user_add_friend"
	get "edges/delfriend" => "edges#user_del_friend"

	get "edges/follow"   => "edges#user_follow_node"
	get "edges/enter"    => "edges#user_enter_group"
	get "edges/visits"   => "edges#user_visits"
	get "edges/lives"    => "edges#user_lives"
	post "edges/update"   => "edges#update"

	get  "/login" => "sessions#new"
	post "/login" => "sessions#create"


	get "/home"               => "home#show"
	get "/home/:edge"         => "home#show"

	get "/home/contacts"      => "people#index"
	get "/home/contacts/new"  => "people#new"


	#get "/home/:p"  => "home#index"




	get "/node/:id"           => "public#show"
	#get "/node/:id/:edge" => "public#show_edge"

  # Example of regular route:
  #   get 'products/:id' => 'catalog#view'

  # Example of named route that can be invoked with purchase_url(id: product.id)
  #   get 'products/:id/purchase' => 'catalog#purchase', as: :purchase

  # Example resource route (maps HTTP verbs to controller actions automatically):
  #   resources :products

  # Example resource route with options:
  #   resources :products do
  #     member do
  #       get 'short'
  #       post 'toggle'
  #     end
  #
  #     collection do
  #       get 'sold'
  #     end
  #   end

  # Example resource route with sub-resources:
  #   resources :products do
  #     resources :comments, :sales
  #     resource :seller
  #   end

  # Example resource route with more complex sub-resources:
  #   resources :products do
  #     resources :comments
  #     resources :sales do
  #       get 'recent', on: :collection
  #     end
  #   end

  # Example resource route with concerns:
  #   concern :toggleable do
  #     post 'toggle'
  #   end
  #   resources :posts, concerns: :toggleable
  #   resources :photos, concerns: :toggleable

  # Example resource route within a namespace:
  #   namespace :admin do
  #     # Directs /admin/products/* to Admin::ProductsController
  #     # (app/controllers/admin/products_controller.rb)
  #     resources :products
  #   end
end

app/models/project.rb
class Project < Dbnode
	attr_accessor :name, :brief, :description, :is_public

	has_many "authors",   edge:"has_projects", type: "in"
	has_many "members",   edge:"participes",   type: "in"
	has_many "followers", edge:"follows",      type: "in"

	def create(author)
		save
		self.authors.put(author)
		if ( _local_id.present? )
			self.authors.put(_local_id)
		end
	end


	def thumbnail
		if File.exists?("public/imagens/#{@id}.jpg")
			return "/imagens/#{@id}.jpg"
		else
			return "/defaults/project.png"
		end
	end
end

app/controllers/projects_controller.rb
class ProjectsController < ApptNodeController

	def index
		@projects = Project.all
		nodepkg_render("index",@projects)
	end


protected
	def node_create(args={})
		return Project.new(args)
	end

	def node_params
		params.require(:project).permit(:name, :brief, :description, :_local_id)
	end

	def create_obj(args={})
		return Project.new(args)
	end
end

app/helpers/projects_helper.rb
module ProjectsHelper
end

app/views/projects/_form.html.erb
<%= form_for(@node) do |f| %>
  <% if @node.errors.any? %>
    <div id="error_explanation">
      <h2><%= pluralize(@node.errors.count, "error") %> prohibited this project from being saved:</h2>

      <ul>
      <% @node.errors.full_messages.each do |message| %>
        <li><%= message %></li>
      <% end %>
      </ul>
    </div>
  <% end %>

  <div class="field">
    <%= f.label :name %><br>
    <%= f.text_field :name, class:"form-control" %>
  </div>
  <div class="field">
    <%= f.label :brief %><br>
    <%= f.text_area :brief, class:"form-control", rows: 3 %>
  </div>
  <div class="field">
    <%= f.label :description %><br>
    <%= f.text_area :description, class:"form-control", rows: 10 %>
  </div>
	<%= f.hidden_field :_local_id, class:"form-control" %>
  <div class="actions">
    <%= f.submit class:"btn btn-primary btn-lg btn-block"%>
  </div>
<% end %>

app/views/projects/_show.html.erb
<div class="row"><div class="col-12">
	<div class="jumbotron p-3 p-md-5 text-white rounded bg-dark"><div class="col-md-6 px-0">
		<h1 class="display-4 font-italic"><%=node.name%></h1>
		<p class="lead my-3"><%=node.description%></p>
	</div></div>
</div></div>


<div class="row"><div class="col-8">
	<p id="notice"><%= notice %></p>

	<ul class="nav">
		<li class="nav-item">
			<%=followed_button(node,user)%>
		</li>
		<li class="nav-item">
			<%=button_enter(node,user)%>
		</li>
		<li class="nav-item">
		<a class="nav-link" href="#">Link</a>
		</li>
		<li class="nav-item">
		<a class="nav-link disabled" href="#">Disabled</a>
		</li>
	</ul>


<%=title "Cronograma","0"%>


<%=title "Tarefas","0"%>

<%=link_to "Nova Tarefa","/tasks/new"%>






<div class="card mb-4 box-shadow">
	<img class="card-img-top" data-src="holder.js/100px225?theme=thumb&bg=55595c&fg=eceeef&text=Thumbnail" alt="Card image cap">
	<div class="card-body">
	<p class="card-text">This is a wider card with supporting text below as a natural lead-in to additional content. This content is a little bit longer.</p>
	<div class="d-flex justify-content-between align-items-center">
	<div class="btn-group">
	<button type="button" class="btn btn-sm btn-outline-secondary">View</button>
	<button type="button" class="btn btn-sm btn-outline-secondary">Edit</button>
	</div>
	<small class="text-muted">9 mins</small>
	</div>
	</div>
</div>



</div><div class="col-4">

	<h2>Participantes</h2>
		<div class="row"><%node.members.all.each do |member|%>
			<div class="col-2"><%=card(member)%></div>
		<%end%></div>
		<h2>Criadores</h2>
		<div class="row"><%node.authors.all.each do |author|%>
			<div class="col-2"><%=card(author)%></div>
		<%end%></div>
		<h2>Seguidores</h2>
		<div class="row"><%node.followers.all.each do |unit|%>
			<div class="col-2"><%=card(unit)%></div>
		<%end%></div>
	</div>

</div>

app/views/projects/edit.html.erb
<div class="container">
	<h1 align="center">Editing Project</h1><hr>
	<div class="row"><div class="col-3" align="center">
		<%=image_md(@node)%>
	</div><div class="col-6">
		<%= form_for(@node, as: "node", url: "/edges/update?akk=thumbnail", method:"post") do |f| %>
			<%= f.hidden_field :id %>
			<%= f.label :file %>
			<%= f.file_field :bitstream %>
			<%= f.submit "Upload novo Thumbnail", class: "btn btn-primary" %>
		<% end %>
	</div></div><hr>
	<%= render 'form' %>
</div>

app/views/projects/index.html.erb
<p id="notice"><%= notice %></p>

<%=title "Projetos",count:nodepkg.count%>
<table class="table">
	<thead><tr>
		<th>Nome</th>
		<th>Particpantes</th>
		<th>Seguidores</th>
		<th colspan="3"></th>
	</tr></thead>
	<tbody><% @projects.each do |proj| %><tr>
		<td><%=image_sm(proj)%><%=link_to proj.name, proj.path %></td>
		<td><%= proj.members.count + proj.authors.count %></td>
		<td><%= proj.followers.count %></td>
	</tr><% end %></tbody>
</table><br>

<%if node.present?%>
	<%= link_to 'New Project', "#{node.path}/projects/new" %>
<%else%>
	<%= link_to 'New Project', new_project_path %>
<%end%>

app/views/projects/new.html.erb
<div class="container">
	<h1 align="center">Novo Projeto</h1>
	<%= render 'projects/form' %>
</div>

app/views/projects/show.html.erb
<div class="row"><div class="col-12">
	<div class="jumbotron p-3 p-md-5 text-white rounded bg-dark"><div class="col-md-6 px-0">
		<h1 class="display-4 font-italic"><%=node.name%></h1>
		<p class="lead my-3"><%=node.brief%></p>
	</div></div>
</div></div>


<div class="container"><div class="row"><div class="col-8">
	<p id="notice"><%= notice %></p>

	<ul class="nav">
		<%if user.present?%>
		<li class="nav-item">
			<%=followed_button(node,user)%>
		</li>
		<li class="nav-item">
			<%=button_enter(node,user)%>
		</li>
		<%end%>
		<li class="nav-item">
		<a class="nav-link" href="#">Link</a>
		</li>
		<li class="nav-item">
		<a class="nav-link disabled" href="#">Disabled</a>
		</li>
	</ul>


<%=node.description.html_safe%>

<%=title "Cronograma"%>


<%=title "Tarefas"%>

<%=link_to "Nova Tarefa","/tasks/new"%>






<div class="card mb-4 box-shadow">
	<img class="card-img-top" data-src="holder.js/100px225?theme=thumb&bg=55595c&fg=eceeef&text=Thumbnail" alt="Card image cap">
	<div class="card-body">
	<p class="card-text">This is a wider card with supporting text below as a natural lead-in to additional content. This content is a little bit longer.</p>
	<div class="d-flex justify-content-between align-items-center">
	<div class="btn-group">
	<button type="button" class="btn btn-sm btn-outline-secondary">View</button>
	<button type="button" class="btn btn-sm btn-outline-secondary">Edit</button>
	</div>
	<small class="text-muted">9 mins</small>
	</div>
	</div>
</div>



</div><div class="col-4">

	<h2>Participantes</h2>
		<div class="row"><%node.members.all.each do |member|%>
			<div class="col-2"><%=card(member)%></div>
		<%end%></div>
		<h2>Criadores</h2>
		<div class="row"><%node.authors.all.each do |author|%>
			<div class="col-2"><%=card(author)%></div>
		<%end%></div>
		<h2>Seguidores</h2>
		<div class="row"><%node.followers.all.each do |unit|%>
			<div class="col-2"><%=card(unit)%></div>
		<%end%></div>
	</div>

</div></div>