config/routes.rb
Rails.application.routes.draw do

	root 'application#index'

	resources :groups do
		get "members"      => "groups#index_members"
		get "news"         => "groups#index_news"
		get "groups"       => "groups#index_groups"
		get "groups/new"   => "groups#local_new_group"
		get "projects"     => "groups#index_projects"
		get "projects/new" => "groups#local_new_project"
	end

	resources :articles
	resources :projects
	resources :units
	resources :users do
		get "friends"      => "users#index_friends"
		get "news"         => "users#index_news"
		get "groups"       => "users#index_groups"
		get "projects"     => "users#index_projects"
	end

	resources :places
	resources :people

	get "edges/addfriend" => "edges#user_add_friend"
	get "edges/delfriend" => "edges#user_del_friend"

	get "edges/follow"   => "edges#user_follow_node"
	get "edges/enter"    => "edges#user_enter_group"
	get "edges/visits"   => "edges#user_visits"
	get "edges/lives"    => "edges#user_lives"
	post "edges/update"   => "edges#update"

	get  "/login" => "sessions#new"
	post "/login" => "sessions#create"


	get "/home"               => "home#show"
	get "/home/:edge"         => "home#show"

	get "/home/contacts"      => "people#index"
	get "/home/contacts/new"  => "people#new"


	#get "/home/:p"  => "home#index"




	get "/node/:id"           => "public#show"
	#get "/node/:id/:edge" => "public#show_edge"

  # Example of regular route:
  #   get 'products/:id' => 'catalog#view'

  # Example of named route that can be invoked with purchase_url(id: product.id)
  #   get 'products/:id/purchase' => 'catalog#purchase', as: :purchase

  # Example resource route (maps HTTP verbs to controller actions automatically):
  #   resources :products

  # Example resource route with options:
  #   resources :products do
  #     member do
  #       get 'short'
  #       post 'toggle'
  #     end
  #
  #     collection do
  #       get 'sold'
  #     end
  #   end

  # Example resource route with sub-resources:
  #   resources :products do
  #     resources :comments, :sales
  #     resource :seller
  #   end

  # Example resource route with more complex sub-resources:
  #   resources :products do
  #     resources :comments
  #     resources :sales do
  #       get 'recent', on: :collection
  #     end
  #   end

  # Example resource route with concerns:
  #   concern :toggleable do
  #     post 'toggle'
  #   end
  #   resources :posts, concerns: :toggleable
  #   resources :photos, concerns: :toggleable

  # Example resource route within a namespace:
  #   namespace :admin do
  #     # Directs /admin/products/* to Admin::ProductsController
  #     # (app/controllers/admin/products_controller.rb)
  #     resources :products
  #   end
end

app/models/unit.rb
class Unit < Dbnode
	attr_accessor :code, :name

	def save
		super
		FileUtils.mkdir_p "db/filesystem/#{@id}"
	end
end

app/controllers/units_controller.rb
class UnitsController < ApplicationController
  before_action :set_unit, only: [:show, :edit, :update, :destroy]

  # GET /units
  # GET /units.json
  def index
    @units = Unit.all
  end

  # GET /units/1
  # GET /units/1.json
  def show
  end

  # GET /units/1/edit
  def edit
  end

  # POST /units
  # POST /units.json
  def create
    respond_to do |format|
        format.html { render "Error" }
        format.json { render json: @unit.errors, status: :unprocessable_entity }
    end
  end

  # PATCH/PUT /units/1
  # PATCH/PUT /units/1.json
  def update
    respond_to do |format|
      if @unit.update(unit_params)
        format.html { redirect_to @unit, notice: 'Unit was successfully updated.' }
        format.json { render :show, status: :ok, location: @unit }
      else
        format.html { render :edit }
        format.json { render json: @unit.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /units/1
  # DELETE /units/1.json
  def destroy
    @unit.destroy
    respond_to do |format|
      format.html { redirect_to units_url, notice: 'Unit was successfully destroyed.' }
      format.json { head :no_content }
    end
  end

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_unit
      @unit = Unit.find(params[:id])
    end

    # Never trust parameters from the scary internet, only allow the white list through.
    def unit_params
      params.require(:unit).permit(:code, :name)
    end
end

app/helpers/units_helper.rb
module UnitsHelper
end

app/views/units/_form.html.erb
<%= form_for(@unit) do |f| %>
  <% if @unit.errors.any? %>
    <div id="error_explanation">
      <h2><%= pluralize(@unit.errors.count, "error") %> prohibited this unit from being saved:</h2>

      <ul>
      <% @unit.errors.full_messages.each do |message| %>
        <li><%= message %></li>
      <% end %>
      </ul>
    </div>
  <% end %>

  <div class="field">
    <%= f.label :code %><br>
    <%= f.text_field :code %>
  </div>
  <div class="field">
    <%= f.label :name %><br>
    <%= f.text_field :name %>
  </div>
  <div class="actions">
    <%= f.submit %>
  </div>
<% end %>

app/views/units/edit.html.erb
<h1>Editing Unit</h1>

<%= render 'form' %>

<%= link_to 'Show', @unit %> |
<%= link_to 'Back', units_path %>

app/views/units/index.html.erb
<p id="notice"><%= notice %></p>

<h1>Listing Units</h1>

<table class="table">
  <thead>
    <tr>
      <th>Tipo</th>
      <th>Code</th>
      <th>Name</th>
      <th colspan="1"></th>
    </tr>
  </thead>

  <tbody>
    <% @units.each do |unit| %>
      <tr>
        <td><%= unit.classe %></td>
        <td><%= unit.code %></td>
        <td><%= unit.name %></td>
        <td>
			<%= link_to 'Edit', edit_unit_path(unit) %>

		</td>
      </tr>
    <% end %>
  </tbody>
</table>

<br>

app/views/units/show.html.erb
<p id="notice"><%= notice %></p>

<p>
  <strong>Code:</strong>
  <%= @unit.code %>
</p>

<p>
  <strong>Name:</strong>
  <%= @unit.name %>
</p>

<%= link_to 'Edit', edit_unit_path(@unit) %> |
<%= link_to 'Back', units_path %>